# Generated by Django 2.2.6 on 2019-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_gender', models.CharField(default='', max_length=1)),
                ('user_mobile', models.CharField(default='', max_length=70)),
                ('user_image', models.ImageField(default='', upload_to='login/userimage')),
                ('user_dob', models.DateField(null=True)),
                ('user_description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
