# Generated by Django 2.2.5 on 2019-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_dob',
            field=models.DateField(null=True),
        ),
    ]
