# Generated by Django 2.2.6 on 2019-10-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191020_1716'),
        ('ypdb', '0005_delete_watched'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watched_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('ypdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ypdb.Ypdb')),
            ],
        ),
    ]
