# Generated by Django 2.2.6 on 2019-10-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watched_id',
            new_name='watchlist_id',
        ),
    ]
