# Generated by Django 2.2.6 on 2019-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ypdb',
            fields=[
                ('ypdb_id', models.AutoField(primary_key=True, serialize=False)),
                ('ypdb_title', models.CharField(max_length=100)),
                ('ypdb_year', models.CharField(default='', max_length=50)),
                ('ypdb_type', models.CharField(default='', max_length=50)),
                ('ypdb_poster', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
