# Generated by Django 2.2.6 on 2019-10-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ypdb', '0004_auto_20191020_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
